### ISSUE TITLE
Address invalid / outdated API key

### ISSUE THREAD

**Issue by Izodine** [throwrocks/android-udacity-reviews#28]
The application crashes when refreshing, if the API key is invalid or outdated.

**Comment by throwrocks** [comment]
I'm going to test passing a wrong key to see what kind of response I get and document it here. I'm also going to store my current key so I can try it later when it's expired to see if it's the same error response or a different one.

**Comment by throwrocks** [comment]
This is fixed now. I'm passing back an error code when the results are null. 

![screenshot_20160824-225300](https://cloud.githubusercontent.com/assets/15916568/17956258/2452b2fe-6a4e-11e6-8c41-a49685658efb.png)

Please test. You can pass a bad API key by hard-coding it in `MainActivity` here:

```
 String API_KEY = BuildConfig.UDACITY_REVIEWER_API_KEY;
        // Hardcode bad key here
        editor.putString("api_key", API_KEY);
        editor.apply();
```
