### ISSUE TITLE
app crashes on refreshing 'Reviews' page

### ISSUE THREAD

**Issue by msheahen** [throwrocks/android-udacity-reviews#37]
This seems to happen when I test on devices/emulators that have near-full memory.  The app will open, but when pulling data down on refresh, the app crashes after some time.

from the log:

```
                                                                       --------- beginning of crash
```

09-02 12:56:52.734 3087-3186/rocks.athrow.android_udacity_reviews A/libc: Fatal signal 7 (SIGBUS), code 2, fault addr 0xa0f51000 in tid 3186 (AsyncTask #2)

It would be nice to limit the number well pull down in this case, or at least find some error handling to prevent a full-on crash.

**Comment by throwrocks** [comment]
@msheahen please try now. I changed the AsyncTask to IntentService. Also, you can now set the API Key in the Settings, instead of in the build.gradle file.
